-- AMAZON
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('FIRE 7', 1, 1);

-- APPLE
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD 2 (A1396)', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD 4', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD 6 TOUCH', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD 7G', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD MINI 1', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD MINI 2', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD MINI 3', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD MINI 4', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD MINI 5', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPAD MINI 6', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 11', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 11 PRO', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 11 PRO MAX', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 12', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 12 MINI', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 12 PRO', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 12 PRO MAX', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 13 PRO MAX', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 14 PRO', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 5 SE', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 5C', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 5G', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 5S', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 6G', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 6G PLUS', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 6S', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 6S PLUS', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 7 PLUS', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 7G', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 8G', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE 8G PLUS', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE X', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE XR', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE XS', 1, 2);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('IPHONE XS MAX', 1, 2);

-- HUAWEI
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('HONOR 8X', 1, 3);

-- LENOVO
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('P11 PLUS', 1, 4);

-- LG
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K10', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K10 2017', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K10 POWER', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K10 PRO', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K11', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K11 PLUS', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K12', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K12 MAX', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K12 PLUS', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K12 PRIME', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K22', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K22 PLUS', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K40', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K40S', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K41S', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K42', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K50S', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K51', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K51S', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K52', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K61', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K62', 1, 5);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('K9', 1, 5);

-- LG NOKIA
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('TESTE', 1, 6);

-- MOTOROLA
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E13', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E20', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E22', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E32', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E40', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E5', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E5 PLAY', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E5 PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E6 PLAY', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E6 PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E6S', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E7 / E7 POWER', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('E7 PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('EDGE', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('EDGE +', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('EDGE 20', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('EDGE 20 LITE', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('EDGE 30 5G', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('EDGE 30 ULTRA', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('EDGE 40 NEO', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('EDGE 50 FUSION', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G 5G', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G 5G PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G10', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G100', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G13', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G14', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G20', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G22', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G30', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G31', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G34', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G42', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G5', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G5 PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G50', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G51', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G52', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G53', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G54', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G5S', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G5S PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G6', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G6 PLAY', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G6 PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G60', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G60S', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G7', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G7 PLAY', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G7 PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G7 POWER', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G71', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G73', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G8', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G8 PLAY', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G8 PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G8 POWER', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G8 POWER LITE', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G82 5G', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G9', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G9 PLAY', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G9 PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G9 POWER', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ONE', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ONE ACTION', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ONE FUSION', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ONE FUSION PLUS', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ONE HYPER', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ONE MACRO', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ONE VISION', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ONE ZOOM', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('RAZR 40', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('X4', 1, 7);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('Z3 PLAY', 1, 7);

-- MULTILASER
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M10A', 1, 8);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M7S PLUS', 1, 8);

-- NOKIA
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('C20 (TA-1339)', 1, 9);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('G11 PLUS', 1, 9);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('TA-1333', 1, 9);

-- Oppo
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('Oppo A40', 1, 10);

-- POSITIVO
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('INFINIX HOT 11', 1, 11);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('INFINIX HOT 11S', 1, 11);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('INFINIX HOT 20I', 1, 11);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('INFINIX HOT 30', 1, 11);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('INFINIX HOT 30I', 1, 11);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('INFINIX NOTE 30 5G', 1, 11);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('INFINIX SMART 8', 1, 11);

-- SAMSUNG
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A01', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A01 CORE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A02', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A02S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A03', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A03 CORE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A03S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A04', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A04E', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A04S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A10', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A10S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A11', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A12', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A13', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A14', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A15', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A16 5G', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A20', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A20S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A21', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A21S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A22 4G', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A22 5G', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A23', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A23 5G', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A30', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A30S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A31', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A32 4G', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A32 5G', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A33', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A35', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A5', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A5 2015', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A5 2016', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A5 2017', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A50', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A51', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A52', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A52S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A53', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A54', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A6', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A6 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A7', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A7 2016', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A7 2017', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A7 2018', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A70', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A71', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A72', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A73', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A8', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A8 2018', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A8 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A80', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A9 2016', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('A9 2018', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('GRAN 2 DUOS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('GRAN DUOS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('GRAN PRIME DUOS TV', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J1', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J1 2016', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J1 MINI', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J1 MINI PRIME', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J2', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J2 CORE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J2 PRIME', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J3', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J3 2016', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J3 PRIME', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J4', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J4 CORE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J4 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J5', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J5 2016', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J5 METAL', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J5 PRIME', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J5 PRO', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J6', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J6 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J7', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J7 2016', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J7 DUO', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J7 METAL', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J7 NEO', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J7 PRIME', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J7 PRIME 2 TV', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J7 PRO', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('J8', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M10', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M12', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M13', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M14', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M20', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M21S', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M23', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M30', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M31', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M34', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M51', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M52', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('M62', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('NOTE 10', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('NOTE 10 +', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('NOTE 10 LITE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('NOTE 20', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('NOTE 20 ULTRA', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('NOTE 8', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('NOTE 9', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ON 7 DISPLAY', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('ON 7 TOUCH', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('P205', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('P610/P613/P615/P619', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('P615', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S10', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S10 LITE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S10 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S10E', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S20', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S20 FE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S20 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S21', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S21 FE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S21 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S21 ULTRA', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S22', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S22 ULTRA', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S23 FE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S23 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S23 ULTRA', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S24 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S6', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S6 EDGE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S6 EDGE PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S7', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S7 EDGE', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S8', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S8 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S9', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('S9 PLUS', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T110', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T116BU', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T220', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T230', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T280', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T290', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T295', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T385', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T500/T505', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T515', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T560', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T595', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('T875', 1, 12);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('X200', 1, 12);

-- XIAOMI
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('11T', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('12 LITE 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('BLACK SHARK', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('BLACK SHARK 2', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('BLACK SHARK 3', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('BLACK SHARK 4', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('F2', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 11', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 11 LITE', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 11 LITE 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 11 LITE 5G NE', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('Mi 12', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 12T', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 5', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 8', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 8 LITE', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 8 PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 9', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 9 LITE', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 9 SE', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 9T', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI 9T PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI A1', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI A2', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI A2 LITE', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI A3', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI MAX 2', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI MAX 3', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI MIX 2', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI MIX 3', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI NOTE 10', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('MI NOTE 10 LITE / PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO C31', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO F3', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO F4', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO F4 GT', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO F5', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO M3 / REDMI 9T', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO M3 PRO 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO M4', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO M4 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO M4 PRO 4G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO M5', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO M5S', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO X3 / X3 PRO / X3 NFC', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO X3 GT', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO X4 GT', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO X4 PRO 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO X5 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO X5 PRO 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO X6 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCO X6 PRO 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('POCOPHONE F1', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 10 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 10 A', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 10 PRIME', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 10C / 10 POWER', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 11 PRIME', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 11T PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 12 4G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 12C', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 13C / POCO C65', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 14C', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 7', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 7A', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 8', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 8 PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 8A', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 9', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 9 PRIME', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 9 T', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 9A / 9I', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI 9C', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 10 4G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 10 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 10 PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 10 PRO 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 10 PRO MAX', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 10S', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 11 4G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 11 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 11 PRO 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 11 PRO PLUS 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 11S 4G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 11S 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 12', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 12 PRO 5G', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 12S', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 13', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 13 PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 13 PRO PLUS', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 7', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 8', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 8 PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 8T', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 9', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 9 PRO', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI NOTE 9S', 1, 13);
INSERT INTO `modelo` (`nome`, `tipo_id`, `marca_id`) VALUES ('REDMI PAD SE', 1, 13); 